#include "../tree-sitter/lib/src/lib.c"
#include "../tree-sitter-c/src/parser.c"

#include "node_printer.c"
#include "node_printer.c"
#include "truncate.c"
#include "OArg.c"
#include "iteration.c"
#include "ruler.c"
#include "indentation.c"
#include "tree_navigator.c"
#include "Pars.c"
#include "main.c"
